user_index:
    path:     /
    defaults: { _controller: AppBundle:User:index }

user_new:
    path:     /new
    defaults: { _controller: AppBundle:User:new }

user_update:
    path:     /{id}/update
    defaults: { _controller: AppBundle:User:update, id : null }