easy_admin:

    site_name: '%env(APP_SITE_NAME)%'
    show:
        max_results: 20
    list:
        actions:
            - { name: 'show', icon: 'eye', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }

    design:
        brand_color: '#3C8DBC'
#        form_theme: ['bootstrap_3_layout.html.twig']
        menu:
            - { label: 'Administración', route: '' }
#            - { label: 'Condición Jugador', entity: CondicionJugador , default: true}
            - { label: 'Usuarios', entity: User }
        assets:
            favicon: 'bundles/app/img/logo.png'