easy_admin:
  entities:
      User:
        class: App\Entity\User
        label: 'Usuario'
        list:
          fields:
            - { property: 'username' }
            - { property: 'email', type: 'email' }
            - { property: 'enabled' }
        form:
          title: 'Crear %%entity_label%%'
          fields:
            - username
            - email
            - enabled
            # if administrators are allowed to edit users' passwords and roles, add this:
            - { property: 'plainPassword', type: 'text', type_options: { required: false, mapped: false, label: 'Password' } }
            - { property: 'roles', type: 'choice', type_options: { multiple: true, expanded: false, choices:
              { 'ROLE_USER': 'ROLE_USER',
                'ROLE_ADMIN': 'ROLE_ADMIN',
              }
            }
            }